apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: hello-app-$VERSION
  region: eu-central-1
  tags:
    project: udastone

iam:
  withOIDC: true

nodeGroups:
  - name: flask-hello-app-$VERSION
    instanceType: t2.small
    amiFamily: AmazonLinux2
    desiredCapacity: 1
    minSize: 1
    maxSize: 2
    volumeSize: 80
    ssh:
      allow: true
      publicKeyName: udacity