apiVersion: apps/v1
kind: Deployment
metadata:
  name: udastone-deployment
  labels:
    app: udastone-hello-app
    
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: udastone-hello-app
  template:
    metadata:
      labels:
        app: udastone-hello-app
        
    spec:
      containers:
      - name: udacity-capstone
        image: tr3mo89/udacity-capstone
        imagePullPolicy: Always
        ports:
        - containerPort: 80
  
---
apiVersion: v1
kind: Service
metadata:
  name: capstone-loadbalancer
  labels:
    app: udastone-hello-app
    
spec:
  selector:
    app: udastone-hello-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer