version: 2.1

jobs:
  linting:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      - run:
          name: install lint
          command: |
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64
            chmod +x /bin/hadolint
      - run: 
          name: lint the dockerfile
          command: |
            pwd
            ls -la
            make lint
  
  build_image:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      - run: 
          name: build image
          command: |
            docker build -t udacity/flask:latest ..
  
  
  push_image:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      - run:
          name: set dockerpath
          command: |
            dockerpath="tr3mo89/udacity-capstone"
      - run: 
          name: tag_image
          command: |
            docker tag udacity/flask:latest $dockerpath:latest
      - run:
          name: push image
          command: |
            docker push $dockerpath


workflows:
  application-pipeline:
    jobs:
      - linting
      - build_image:
          requires: [linting]
      - push_image:
          requires: [build_image]