version: 2.1

orbs:
  docker: circleci/docker@2.0.1

commands:
  install-dependencies:
    description: install dependencies
    steps:
      - run:
          name: install dependencies
          command: |
            pip install --upgrade pip && pip install -r requirements.txt
            pip install cython
            pip install pandas
  install-kubectl:
    description: install kubectl
    steps:
      - run:
          name: install kubectl
          command: |
            apt-get update
            apt-get install -y apt-transport-https ca-certificates curl
            curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
            echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | tee /etc/apt/sources.list.d/kubernetes.list
            apt-get update
            apt-get install -y kubectl
           #  kubectl version
  install-minikube:
    description: install minikube
    steps:
      - run:
          name: install minikube
          command: |
            curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 \
              && chmod +x minikube
            cp minikube /usr/local/bin && rm minikube
            minikube version
  install-eksctl:
    description: install eksctl on ubuntu
    steps:
      - run:
          name: install eksctl
          command: |
            curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
            mv /tmp/eksctl /usr/local/bin
            eksctl version

jobs:
  linting:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      - install-dependencies
      - run:
          name: install lint
          command: |
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64
            chmod +x /bin/hadolint
            hadolint --version
      - run:
          name: run lint
          command: |
            make lint
     # - save_cache:
     #     paths:
     #       - ./.capstone  
     #     key: v1-dependencies-{{ checksum "hello_app/requirements.txt" }}

  
  handle_docker_image:
    docker:
      - image: tr3mo89/ubuntu-20.04-docker
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run: 
          name: build image
          command: |
            docker build -t $dockerpath:latest .
      - run: 
          name: tag image
          command: |
            docker tag $dockerpath:latest $dockerpath:latest
      - run:
          name: login to dockerhub
          command: |
            docker login -u $dockerId -p $dockerAuth
      - run:
          name: push image
          command: |
            docker push $dockerpath:latest

  kubernetes_stuff:
    docker:
      - image: tr3mo89/ubuntu-20.04-docker
    steps:
      - checkout
      - install-kubectl
      - install-minikube
      - install-eksctl
      - run:
          name: start minikube
          command: minikube start
      - run:
          name: run flask app
          command: |
            kubectl run flask --image=$dockerpath --port=8000
            kubectl port-forward flask 8000:80


workflows:
  application-pipeline:
    jobs:
      #- linting
      #- handle_docker_image
      - kubernetes_stuff 